name: Build-Push-Deploy
env:
  IMAGE_REPOSITORY: "quay.io/omidiyanto/nextjs-grpc"
  TAGS: "frontend"
  QUAYIO_USER: "omidiyanto"
  QUAYIO_PASSWORD: ${{ secrets.QUAYIO_PASSWORD }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  BACKEND_URL: "grpc:2701"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Registry
      run: echo "${{ env.QUAYIO_PASSWORD }}" | docker login quay.io -u ${{ env.QUAYIO_USER }} --password-stdin
    - name: Build the Docker image
      run: docker build -t ${{ env.IMAGE_REPOSITORY }}:${{ env.TAGS }} --build-arg ARG_BACKEND_URL=${{ env.BACKEND_URL }} .
    - name: Store Image to Registry
      run: docker push ${{ env.IMAGE_REPOSITORY }}:${{ env.TAGS }}

  deploy-k8s:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: create kubeconfig
      run: |
        mkdir -p ${HOME}/.kube
        echo "${{ env.KUBE_CONFIG }}" | base64 -d > ${HOME}/.kube/config
    - name: kubectl checking
      run: kubectl get nodes
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Apply k8s yml file for Deployment
      run: |
        kubectl apply -f Kubernetes/
    - name: Access the Endpoint when app ready
      run: |
        echo "================== Access The App ==================="
        echo ""
        echo "URL = https://$(kubectl get ingress nextjs-grpc-frontend -o jsonpath='{.spec.rules[0].host}')"
        echo ""
        echo "====================================================="
